spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: postgres
    password: password

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: Xto4BFsDZ6MsIJaUYMCdxdywou2vHqMM
            client-secret: xsD3QXe1jDEqI6KOq5ojDpkdUFzIRTGqOghiKkozXiiO8g3DOKN9V4M-u-z1P0Je
            scope:
              - openid
              - profile
        provider:
          auth0:
            issuer-uri: https://dev-wh5gdfeyti4ssudx.eu.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-wh5gdfeyti4ssudx.eu.auth0.com/